Repository ethlibrary/EIPs, pull requests merged in 2021-11, with the labels that each got.

#4 doc(zh): translate eip-3
  EIPS/zh/eip-3.md
Labels: 翻译认领

#8 doc: translate comparison
  README.md
Labels: documentation

#9 feat: pr issue template
  ISSUE_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: enhancement
